"""added tables

Revision ID: 1a370cd255bb
Revises:
Create Date: 2024-09-26 11:28:14.049344

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1a370cd255bb'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'template',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'notification',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('template_id', sa.UUID(), nullable=False),
        sa.Column('content_id', sa.UUID(), nullable=False),
        sa.Column('content_value', sa.Text(), nullable=False),
        sa.Column('last_update', sa.DateTime(), nullable=False),
        sa.Column('cron', sa.String(), nullable=False),
        sa.Column('users', sa.ARRAY(sa.String()), nullable=False),
        sa.ForeignKeyConstraint(
            ['template_id'],
            ['template.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    op.drop_table('template')
    # ### end Alembic commands ###
