"""fix notification schema

Revision ID: 54668cfe90b4
Revises: df29efa586bb
Create Date: 2024-10-02 12:05:19.777564

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '54668cfe90b4'
down_revision: str | None = 'df29efa586bb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('type', sa.String(), server_default='email', nullable=False))
    op.add_column('notification', sa.Column('payload', sa.JSON(), nullable=True))
    op.add_column('notification', sa.Column('event_at', sa.DateTime(), nullable=True))
    op.add_column(
        'notification', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False)
    )
    op.add_column(
        'notification', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False)
    )
    op.drop_constraint('notification_template_id_fkey', 'notification', type_='foreignkey')
    op.drop_column('notification', 'content_id')
    op.drop_column('notification', 'template_id')
    op.drop_column('notification', 'last_update')
    op.drop_column('notification', 'name')
    op.drop_column('notification', 'content_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('content_value', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('notification', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('notification', sa.Column('last_update', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('notification', sa.Column('template_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('notification', sa.Column('content_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('notification_template_id_fkey', 'notification', 'template', ['template_id'], ['id'])
    op.drop_column('notification', 'created_at')
    op.drop_column('notification', 'updated_at')
    op.drop_column('notification', 'event_at')
    op.drop_column('notification', 'payload')
    op.drop_column('notification', 'type')
    # ### end Alembic commands ###
