"""fix notification table

Revision ID: 84c875df166e
Revises: 1a370cd255bb
Create Date: 2024-09-26 11:38:27.448084

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '84c875df166e'
down_revision: str | None = '1a370cd255bb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification', 'content_id', existing_type=sa.UUID(), nullable=True)
    op.alter_column('notification', 'content_value', existing_type=sa.TEXT(), type_=sa.String(), nullable=True)
    op.alter_column('notification', 'cron', existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification', 'cron', existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column('notification', 'content_value', existing_type=sa.String(), type_=sa.TEXT(), nullable=False)
    op.alter_column('notification', 'content_id', existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
