"""fix notification table2

Revision ID: 88d636afe6f6
Revises: 84c875df166e
Create Date: 2024-09-26 11:40:35.212344

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '88d636afe6f6'
down_revision: str | None = '84c875df166e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'name')
    # ### end Alembic commands ###
