"""fix notification table5

Revision ID: baa5c2cfd488
Revises: c8a3784db6b6
Create Date: 2024-09-26 12:06:23.404242

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'baa5c2cfd488'
down_revision: str | None = 'c8a3784db6b6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
