"""fix notification table4

Revision ID: c8a3784db6b6
Revises: f9927d77b17c
Create Date: 2024-09-26 12:00:13.659605

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'c8a3784db6b6'
down_revision: str | None = 'f9927d77b17c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
