"""fix notification table3

Revision ID: f9927d77b17c
Revises: 88d636afe6f6
Create Date: 2024-09-26 11:45:16.943419

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'f9927d77b17c'
down_revision: str | None = '88d636afe6f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
