[mypy]
plugins = pydantic.mypy

python_version = 3.12
; mypy не будет жаловаться на отсутствующие аннотации типов в библиотеках.
ignore_missing_imports = true
; строгие проверки типов
strict = true
; запрет на использование функций, в которых отсутствуют аннотации типов
disallow_untyped_defs = true
; предупреждать об игнорируемых аннотациях типов
warn_unused_ignores = true
