FROM python:3.12

WORKDIR /opt/app/event_generator

RUN apt-get update -y && apt-get install -y wget

COPY pyproject.toml poetry.lock /opt/app/event_generator/

RUN pip install --no-compile poetry \
 && poetry config virtualenvs.create false \
 && poetry install --no-interaction --no-ansi

COPY . .

EXPOSE 5000

CMD ["./run.sh"]